In [1]:
import pandas as pd

In [2]:
# 1. Load the provided csv file
data = pd.read_csv("countries.csv")

In [3]:
data

,Rank,Code,Name,Capital,Continent,Population,Area_km2,Density_per_km2,Growth Rate,World_Population_Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,468,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572,142,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986,266000,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614,527968,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675,752612,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537,390757,41.7665,1.0204,0.20

In [4]:
data.head()

,Rank,Code,Name,Capital,Continent,Population,Area_km2,Density_per_km2,Growth Rate,World_Population_Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,468,170.5641,1.0100,0.00

In [5]:
data['Name'][0]

'Afghanistan'

In [6]:
data['Capital'][4]

'Andorra la Vella'

In [7]:
# 2. Count the number of rows
len(data)

234

In [8]:
# 3. Count the number of columns
len(data.columns)

10

In [10]:
# 4. Extract one of the columns and store it as a list
countries = data['Name']
countries

0            Afghanistan
1                Albania
2                Algeria
3         American Samoa
4                Andorra
             ...
229    Wallis and Futuna
230       Western Sahara
231                Yemen
232               Zambia
233             Zimbabwe
Name: Name, Length: 234, dtype: object

In [11]:
# 5. Print out the list
for country in countries:
    print(country)

Afghanistan
Albania
Algeria
American Samoa
Andorra
Angola
Anguilla
Antigua and Barbuda
Argentina
Armenia
Aruba
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bermuda
Bhutan
Bolivia
Bosnia and Herzegovina
Botswana
Brazil
British Virgin Islands
Brunei
Bulgaria
Burkina Faso
Burundi
Cambodia
Cameroon
Canada
Cape Verde
Cayman Islands
Central African Republic
Chad
Chile
China
Colombia
Comoros
Cook Islands
Costa Rica
Croatia
Cuba
Curacao
Cyprus
Czech Republic
Denmark
Djibouti
Dominica
Dominican Republic
DR Congo
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Falkland Islands
Faroe Islands
Fiji
Finland
France
French Guiana
French Polynesia
Gabon
Gambia
Georgia
Germany
Ghana
Gibraltar
Greece
Greenland
Grenada
Guadeloupe
Guam
Guatemala
Guernsey
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Hong Kong
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Isle of Man
Israel
Italy
Ivory Coast
Jamaica
Japan
Jersey
Jordan
Kazakhstan
Kenya
Kiribati
Kuwait
Kyrgyzstan
Laos
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
Macau
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Martinique
Mauritania
Mauritius
Mayotte
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Montserrat
Morocco
Mozambique
Myanmar
Namibia
Nauru
Nepal
Netherlands
New Caledonia
New Zealand
Nicaragua
Niger
Nigeria
Niue
North Korea
North Macedonia
Northern Mariana Islands
Norway
Oman
Pakistan
Palau
Palestine
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Puerto Rico
Qatar
Republic of the Congo
Reunion
Romania
Russia
Rwanda
Saint Barthelemy
Saint Kitts and Nevis
Saint Lucia
Saint Martin
Saint Pierre and Miquelon
Saint Vincent and the Grenadines
Samoa
San Marino
Sao Tome and Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Sint Maarten
Slovakia
Slovenia
Solomon Islands
Somalia
South Africa
South Korea
South Sudan
Spain
Sri Lanka
Sudan
Suriname
Sweden
Switzerland
Syria
Taiwan
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Tokelau
Tonga
Trinidad and Tobago
Tunisia
Turkey
Turkmenistan
Turks and Caicos Islands
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
United States Virgin Islands
Uruguay
Uzbekistan
Vanuatu
Vatican City
Venezuela
Vietnam
Wallis and Futuna
Western Sahara
Yemen
Zambia
Zimbabwe

In [12]:
populations = data['Population']
populations

0      41128771
1       2842321
2      44903225
3         44273
4         79824
         ...
229       11572
230      575986
231    33696614
232    20017675
233    16320537
Name: Population, Length: 234, dtype: int64

In [13]:
# 6. Work out the average of populations
total = 0
for pop in populations:
    total += pop

avg = total / len(populations)
print('Average:', avg)

Average: 34074414.70940171

In [14]:
# 7. Put this code inside a function, and call it to work out the average again
def calculate_average(my_list):
    total = 0
    for i in my_list:
        total += i
    avg = total / len(my_list)
    return avg

avg = calculate_average(populations)
print('Average:', avg)

Average: 34074414.70940171